CI: validate deploy manifest for missing files

diff --git a/.github/workflows/ci_tests_run_notebooks.yml b/.github/workflows/ci_tests_run_notebooks.yml
--- a/.github/workflows/ci_tests_run_notebooks.yml
+++ b/.github/workflows/ci_tests_run_notebooks.yml
@@ -34,6 +34,9 @@ jobs:
       - name: Mark repository as safe
         run: git config --global --add safe.directory $GITHUB_WORKSPACE
 
+      - name: Validating manifest
+        run: bash -c 'missing=false; for file in $(cat deployed_notebooks_manifest.in); do if [ ! -f $file ]; then echo "Inconsistent" $file; missing=true; fi; done; if $missing; then exit 1; fi'
+
       - name: Install test dependencies
         run: |
           python -m pip install --upgrade tox
